title: "Ningrum's Page"
email: panggih_kusuma.ningrum@univ-fcomte.fr
avatar: '/assets/images/ning.jpeg'
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/ninglogosmall.png'
favicon: 'assets/images/favicon.ico'
author: PK Ningrum
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Panggih Kusuma Ningrum
    display_name: Panggih Kusuma Ningrum
    avatar: '/assets/images/ning.jpeg'
    email: panggih_kusuma.ningrum@univ-fcomte.fr
    web: https://ningrumdaud.github.io
    twitter: https://twitter.com/ningrum_daud
    description: "Hi! I'm Ning"

# Social
social:
  linkedin: https://www.linkedin.com/in/panggih-kusuma-ningrum
  github: https://github.com/ningrumdaud
  twitter: https://twitter.com/ningrum_daud

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
