title: "Ningrum's Page"
email: panggih_kusuma.ningrum@univ-fcomte.fr
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/ninglogo.png'
favicon: 'assets/images/favicon.ico'
author: PK Ningrum
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Ningrum
    display_name: Ningrum
    avatar: 'assets/images/ning.jpeg'
    email: panggih_kusuma.ningrum@univ-fcomte.fr
    web: https://ningrumdaud.github.io
    twitter: https://twitter.com/ningrum_daud
    description: "Hi! I'm Ning"
  #john:
    #name: John
    #display_name: John
    #avatar: 'assets/images/john.png'
    #email: wowthemesnet@gmail.com
    #web: https://www.wowthemes.net/category/jekyll-themes/
    #twitter: https://twitter.com/wowthemesnet
    #description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  linkedin: https://www.linkedin.com/in/panggih-kusuma-ningrum
  github: https://github.com/ningrumdaud
  twitter: https://twitter.com/ningrum_daud

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
